export const Junks = [
    'Apple pie',
    'Baklava',
    'Beef carpaccio',
    'Beef tartare',
    'Bread pudding',
    'Breakfast burrito',
    'Bruschetta',
    'Cannoli',
    'Ceviche',
    'Cheesecake',
    'Chocolate cake',
    'Chocolate mousse',
    'Crab cakes',
    'Creme brulee',
    'Donuts',
    'Churros',
    'Cup cakes',
    'Falafel',
    'French toast',
    'Macaroni and cheese',
    'Macarons',
    'Paella',
    'Pancakes',
    'Red velvet cake',
    'Spaghetti bolognese',
    'Spaghetti carbonara',
    'Takoyaki',
    'Tiramisu',
    'Tuna tartare',
    'Waffles',
    'Tacos',
    'Strawberry shortcake',
    'Spring rolls',
    'Ravioli',
    'Risotto',
    'Pizza',
    'Lasagna',
    'French fries',
    'Fried calamari',
    'Nachos',
    'Ice cream',
    'Onion rings',
    'Cheese plate',
    'Garlic bread',
    'Grilled cheese sandwich',
    'Hot dog',
]

export const LifeStocks = [
    'Steak',
    'Sashimi',
    'Scallops',
    'Shrimp and grits',
    'Pork chop',
    'Prime rib',
    'Pulled pork sandwich',
    'Oysters',
    'Peking duck',
    'Mussels',
    'Lobster bisque',
    'Lobster roll sandwich',
    'Grilled salmon',
    'Fish and chips',
    'Chicken curry',
    'Chicken quesadilla',
    'Chicken wings',
    'Baby back ribs',
    'Bibimbap',
    'Clam chowder',
    'Foie gras',
    'Hamburger',
    'Gyoza',
    'Omelette',
    'Eggs benedict',
    'Croque madame',
    'Deviled eggs',
    'Escargots',
    'Filet mignon',
    'French onion soup',
    'Frozen yogurt',
]

export const Plantations = [
    'Gnocchi',
    'Greek salad',
    'Miso soup',
    'Hummus',
    'Pad thai',
    'Panna cotta',
    'Pho',
    'Seaweed salad',
    'Sushi',
    'Edamame',
    'Caesar salad',
    'Caprese salad',
    'Carrot cake',
    'Beet salad',
    'Club sandwich',
    'Beignets',
    'Fried rice',
    'Huevos rancheros',
    'Poutine',
    'Ramen',
    'Samosa',
    'Guacamole',
    'Hot and sour soup',
]